const API_BASE_URL_DEVELOPMENT = "https://localhost:7070";
const API_BASE_URL_PRODUCTION =  "";

const ENDPOINTS = {
    GET_ALL_BOOKS: "/api/book",
    GET_BOOK_BY_ID: "/api/book",
    CREATE_BOOK: "/api/book",
    UPDATE_BOOK: "/api/book",
    DELETE_BOOK_BY_ID: "/api/book",
    GET_BOOKS_BY_SEARCH: "/api/book"
}

const development = {
API_URL_GET_ALL_BOOKS: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_ALL_BOOKS}`,
API_URL_GET_BOOK_BY_ID: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_BOOK_BY_ID}`,
API_URL_CREATE_BOOK: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.CREATE_BOOK}`,
API_URL_UPDATE_BOOK: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.UPDATE_BOOK}`,
API_URL_DELETE_BOOK_BY_ID: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.DELETE_BOOK_BY_ID}`,
API_URL_GET_BOOKS_BY_SEARCH: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_BOOKS_BY_SEARCH}`
}

const production = {
    API_URL_GET_ALL_BOOKS: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_ALL_BOOKS}`,
    API_URL_GET_BOOK_BY_ID: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.GET_BOOK_BY_ID}`,
    API_URL_CREATE_BOOK: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.CREATE_BOOK}`,
    API_URL_UPDATE_BOOK: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.UPDATE_BOOK}`,
    API_URL_DELETE_BOOK_BY_ID: `${API_BASE_URL_DEVELOPMENT}${ENDPOINTS.DELETE_BOOK_BY_ID}`,
    API_URL_GET_BOOKS_BY_SEARCH: `${API_BASE_URL_PRODUCTION}${ENDPOINTS.GET_BOOKS_BY_SEARCH}`
    }

const Constants = process.env.NODE_ENV === 'development' ? development : production;

export default Constants;